String restaurantImgName = "images/Sk_Restaurant.jpg";
String restaurantName = "SK Restaurant";
String quotes = "Healthy Foods Wealthy Life";
String login = " Log in";
String email = "Email";
String password = "Password";
String donthave = "Don't have account?";
String createAccount = "Create account";
String forgotPassword = "Forgot Password?";
